# Generated by Django 3.0.4 on 2020-04-01 02:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_basic', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='read',
            field=models.BooleanField(default=False),
        ),
    ]
